// Generated by jextract

package com.icuxika.jextract.win32;

/**
 * {@snippet :
 * typedef struct tagKBDLLHOOKSTRUCT KBDLLHOOKSTRUCT;
 *}
 */
public final class KBDLLHOOKSTRUCT extends tagKBDLLHOOKSTRUCT {

    // Suppresses default constructor, ensuring non-instantiability.
    private KBDLLHOOKSTRUCT() {
    }
}


